---
description: Error del compilador CS0103
title: Error del compilador CS0103
ms.date: 07/20/2015
f1_keywords:
- CS0103
helpviewer_keywords:
- CS0103
ms.assetid: fd1f2104-a945-4dba-8137-8ef869826062
ms.openlocfilehash: 689cebb258fcd75287e8e54630387ae7a6e986c5
ms.sourcegitcommit: d579fb5e4b46745fd0f1f8874c94c6469ce58604
ms.translationtype: HT
ms.contentlocale: es-ES
ms.lasthandoff: 08/30/2020
ms.locfileid: "89134736"
---
# <a name="compiler-error-cs0103"></a>Error del compilador CS0103

El nombre "identifier" no existe en el contexto actual

 Se ha intentado usar un nombre que no existe en la clase, en el [espacio de nombres](../keywords/namespace.md) o en el ámbito. Compruebe la ortografía del nombre y compruebe las directivas y las referencias de ensamblado para asegurarse de que el nombre que intenta usar está disponible.

 Este error suele producirse si declara una variable en un bucle o un bloque de `try` o de `if` y después intenta tener acceso desde un bloque de código que agrega o un bloque de código independiente, como se muestra en el ejemplo siguiente:

```csharp
using System;

class MyClass1
{
    public static void Main()
    {
        try
        {
            // The following declaration is only available inside the try block.
            var conn = new MyClass1();
        }
        catch (Exception e)
        {  
            // The following expression causes error CS0103, because variable
            // conn only exists in the try block.
            if (conn != null)
                Console.WriteLine("{0}", e);
        }
    }
}
```

 En el ejemplo siguiente se resuelve el error:

```csharp
using System;

class MyClass2
{
    public static void Main()
    {
        // To resolve the error in the example, the first step is to
        // move the declaration of conn out of the try block. The following
        // declaration is available throughout the Main method.
        MyClass2 conn = null;
        try
        {
            // Inside the try block, use the conn variable that you declared
            // previously.
            conn = new MyClass2();
        }
        catch (Exception e)
        {
            // The following expression no longer causes an error, because
            // the declaration of conn is in scope.
            if (conn != null)
                Console.WriteLine("{0}", e);
        }
    }
}
```
